# Shared helpers for src/thesis/scripts/b601/*.sh: USB port detection, persistence
# and calibration. Meant to be sourced, not executed; callers must set REPO_ROOT
# and ENV_FILE first.

detect_port() {
    local label="$1"
    local tmpfile
    tmpfile="$(mktemp)"
    {
        echo
        echo "=== Detecting $label port ==="
        echo "When prompted, unplug ONLY the $label's USB cable, then press Enter."
        echo
    } >&2
    PYTHONUNBUFFERED=1 lerobot-find-port < /dev/tty | tee "$tmpfile" >&2
    local port
    port="$(grep -o "The port of this MotorsBus is '[^']*'" "$tmpfile" | sed -E "s/.*'([^']*)'.*/\1/")"
    rm -f "$tmpfile"
    if [[ -z "$port" ]]; then
        echo "Could not determine the $label port from lerobot-find-port output." >&2
        exit 1
    fi
    echo "Detected $label port: $port" >&2
    echo "$port"
}

save_ports_to_env_file() {
    local follower="$1"
    local leader="$2"
    cat > "$ENV_FILE" <<EOF
# Auto-generated by src/thesis/scripts/b601/${CALLER_NAME:-teleop.sh}. Delete this file (or the lines
# below) to force USB port re-detection on the next run.
export THESIS_B601_FOLLOWER_PORT="$follower"
export THESIS_B601_LEADER_PORT="$leader"
EOF
    echo "Saved ports to $ENV_FILE"
}

# deletes the existing calibration file first so calibrate() skips its
# "use existing?" prompt
recalibrate_device() {
    local kind="$1" type="$2" subdir="$3" port="$4" id="$5" extra="$6"
    local calib_root calib_file
    calib_root="$(python -c 'from lerobot.utils.constants import HF_LEROBOT_CALIBRATION; print(HF_LEROBOT_CALIBRATION)')"
    calib_file="$calib_root/$subdir/$type/$id.json"
    if [[ -f "$calib_file" ]]; then
        echo "Removing existing calibration: $calib_file"
        rm -f "$calib_file"
    fi
    echo "Calibrating $type (id=$id). Move it to its ZERO pose when prompted."
    # shellcheck disable=SC2086
    lerobot-calibrate --"${kind}".type="$type" --"${kind}".port="$port" --"${kind}".id="$id" $extra < /dev/tty
}

# populates FOLLOWER_PORT/LEADER_PORT, auto-detecting and persisting to ENV_FILE
resolve_ports() {
    if [[ -f "$ENV_FILE" ]]; then
        source "$ENV_FILE"
    fi

    FOLLOWER_PORT="${FOLLOWER_PORT:-${THESIS_B601_FOLLOWER_PORT:-}}"
    LEADER_PORT="${LEADER_PORT:-${THESIS_B601_LEADER_PORT:-}}"

    local need_detect=0
    if [[ -z "$FOLLOWER_PORT" || ! -e "$FOLLOWER_PORT" ]]; then
        need_detect=1
    fi
    if [[ -z "$LEADER_PORT" || ! -e "$LEADER_PORT" ]]; then
        need_detect=1
    fi

    if [[ "$need_detect" -eq 1 ]]; then
        echo "No saved/valid ports found. Running lerobot-find-port to identify both arms."
        echo "Make sure BOTH the follower and leader are plugged in and powered on before continuing."
        read -r -p "Press Enter when ready..."

        FOLLOWER_PORT="$(detect_port "follower (B601-DM CAN bridge)")"
        LEADER_PORT="$(detect_port "leader (reBot Arm 102)")"
        save_ports_to_env_file "$FOLLOWER_PORT" "$LEADER_PORT"
    fi
}
